export {
  asString,
  asNumber,
  asBoolean,
  asArray,
  isObject,
  safeJsonParse,
  truncate,
  compareFragments,
  compareTimeThenSeq,
  dedupeById,
  formatErrorMessage,
  sumDefinedNumbers,
  firstDefinedNumber,
  epochMillisToIso,
  coerceIso,
  sha1,
} from "@cchistory/domain";
