import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { deriveSessionId, splitUserText } from "./utils.js";

/* -------------------------------------------------------------------------- */
/*  deriveSessionId — claude_code                                             */
/* -------------------------------------------------------------------------- */

describe("deriveSessionId for claude_code", () => {
  const platform = "claude_code" as const;

  test("extracts sessionId from first JSONL line", () => {
    const jsonl = JSON.stringify({
      sessionId: "19d3fbc3-9e1f-49d2-9056-5b56c05ee36d",
      type: "user",
      timestamp: "2026-02-27T15:02:35.368Z",
      message: { role: "user", content: "hello" },
    });
    const buf = Buffer.from(jsonl, "utf8");
    assert.equal(
      deriveSessionId(platform, "/any/path/some-hash.jsonl", buf),
      "sess:claude_code:19d3fbc3-9e1f-49d2-9056-5b56c05ee36d",
    );
  });

  test("subagent files also resolve to parent sessionId", () => {
    const jsonl = JSON.stringify({
      sessionId: "62a0a9bb-aeba-41fb-8ef1-cb3fa0bc9af4",
      type: "user",
      timestamp: "2026-02-27T14:35:42.000Z",
      message: { role: "user", content: "search" },
    });
    const buf = Buffer.from(jsonl, "utf8");
    assert.equal(
      deriveSessionId(platform, "/home/alex/.claude/projects/foo/62a0a9bb/subagents/agent-a4bcc77.jsonl", buf),
      "sess:claude_code:62a0a9bb-aeba-41fb-8ef1-cb3fa0bc9af4",
    );
  });

  test("falls back to basename when no sessionId in content", () => {
    const jsonl = JSON.stringify({ type: "system", timestamp: "2026-01-01T00:00:00Z" });
    const buf = Buffer.from(jsonl, "utf8");
    assert.equal(
      deriveSessionId(platform, "/some/path/conversation.jsonl", buf),
      "sess:claude_code:conversation",
    );
  });

  test("falls back to basename on invalid JSON", () => {
    const buf = Buffer.from("not-json\n", "utf8");
    assert.equal(
      deriveSessionId(platform, "/some/path/broken.jsonl", buf),
      "sess:claude_code:broken",
    );
  });
});

/* -------------------------------------------------------------------------- */
/*  splitUserText — synthetic / injected patterns                             */
/* -------------------------------------------------------------------------- */

describe("splitUserText detects synthetic user-shaped messages", () => {
  // --- Codex patterns ---

  test("Codex <user_action> review result → injected_user_shaped", () => {
    const text = `<user_action>
  <context>User initiated a review task for the file: src/index.ts</context>
  <action>review</action>
</user_action>`;
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Codex <turn_aborted> → injected_user_shaped", () => {
    const text = "<turn_aborted>\nThe user interrupted the previous turn on purpose.";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  // --- Claude Code patterns ---

  test("Claude Code <task-notification> sub-agent callback → injected_user_shaped", () => {
    const text = `<task-notification>
<task-id>aa30b0a8f13602211</task-id>
<tool-use-id>toolu_01HZabc</tool-use-id>
<status>completed</status>
<result>Task completed successfully.</result>
</task-notification>`;
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code continuation summary → injected_user_shaped", () => {
    const text = `This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation.

Analysis:
Let me chronologically analyze the conversation...`;
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code <local-command-caveat> → injected_user_shaped", () => {
    const text = "<local-command-caveat>Caveat: The messages below were generated by a local command.";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code <local-command-stdout> → injected_user_shaped", () => {
    const text = "<local-command-stdout>output from command</local-command-stdout>";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code <bash-input> → injected_user_shaped", () => {
    const text = "<bash-input>ls -la</bash-input>";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code /clear command envelope → injected_user_shaped only", () => {
    const text = "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
  });

  test("Claude Code command envelope with args preserves only the user args as authored text", () => {
    const text = [
      "<command-message>review</command-message>",
      "<command-name>/review</command-name>",
      "<command-args>Audit the command parser regression.</command-args>",
    ].join("\n");
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 2);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
    assert.equal(chunks[1]!.originKind, "user_authored");
    assert.equal(chunks[1]!.text, "Audit the command parser regression.");
  });

  test("Claude Code command envelope without args preserves the command message without XML wrappers", () => {
    const text = "<command-message>review</command-message>\n<command-name>/review</command-name>";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 2);
    assert.equal(chunks[0]!.originKind, "injected_user_shaped");
    assert.equal(chunks[1]!.originKind, "user_authored");
    assert.equal(chunks[1]!.text, "review");
  });

  // --- Genuine user messages must NOT be affected ---

  test("plain user text → user_authored (unchanged)", () => {
    const text = "How do I fix this bug in the parser?";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "user_authored");
  });

  test("Chinese user text → user_authored (unchanged)", () => {
    const text = "为什么不是 51 个成分和 988 个靶点的 dree 值排序的 top ten化合物？";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "user_authored");
  });

  test("user text starting with < but not a known synthetic tag → user_authored", () => {
    const text = "<user_query>\nConduct an in-depth investigation";
    const chunks = splitUserText(text);
    assert.equal(chunks.length, 1);
    assert.equal(chunks[0]!.originKind, "user_authored");
  });
});
